services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudbox-web
    ports:
      - "80:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  redis:
    image: redis:7-alpine
    container_name: cloudbox-redis
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: cloudbox-db
    restart: always
    environment:
      POSTGRES_USER: cloudbox
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudbox
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudbox-celery
    depends_on:
      - redis
      - db
    command: >
      sh -c "celery -A CloudBox.celery_app worker --loglevel=info --concurrency=4"

volumes:
  postgres_data:
