version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudbox_web
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - celery
    volumes:
      - .:/app
    command: /bin/sh start.sh

  redis:
    image: redis:6.2
    container_name: cloudbox_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudbox_celery
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A cloudbox worker --loglevel=info

volumes:
  redis_data:
