services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudbox-web
    ports:
      - "80:8000"
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    command: /bin/sh start.sh

  redis:
    image: redis:7-alpine
    container_name: cloudbox-redis
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: cloudbox-db
    restart: always
    environment:
      POSTGRES_USER: cloudbox
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloudbox
    volumes:
      - cloudbox_postgres_data:/var/lib/postgresql/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cloudbox-celery
    depends_on:
      - redis
      - db
    command: >
      sh -c "celery -A CloudBox.celery_app worker --loglevel=info"
    mem_limit: 256m
  
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    volumes:
      - "./minio/data:/data"
      - "./minio/minio:/minio"
      - "./minio/config:/root/.minio"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      MINIO_ACCESS_KEY: "hongzhe123"
      MINIO_SECRET_KEY: "hongzhe123"
    command: server /data --console-address ":9010"
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
    ports:
      - "9010:9010"
      - "9000:9000"

volumes:
  cloudbox_postgres_data:
    name: "cloudbox_postgres_data"